React task 1 update
chelovek-gorod/EPAM-React pull request #1
Opened 2021-09-13 12:17 UTC by chelovek-gorod

2021-09-28 21:19 UTC, broshkabro commented
1. Study the git-flow. You should not commit to `the main` branch directly. 
2. The structure of your app should be the following:
![image](https://user-images.githubusercontent.com/18407086/135166599-871896b7-e489-42aa-ad01-57523170413b.png)
3. Create a separate folder for the components and move them into it. Move all images into a separate folder as well. You should get the following folder structure:
![image](https://user-images.githubusercontent.com/18407086/135167148-d3b604c7-0063-450d-9e0a-ff056c058bc1.png)

2021-09-28 21:20 UTC, broshkabro requested changes
please address the comments above

2021-10-04 06:41 UTC, chelovek-gorod commented
Done

2021-10-04 11:08 UTC, broshkabro commented on src/App/App.js
> +    <div className="App">
please use kebab case for class names

2021-10-04 11:08 UTC, broshkabro commented on src/App/App.js
> +
remove extra spaces

2021-10-04 15:31 UTC, broshkabro commented on src/components/Avatar/Avatar.js
> +      <img src={avatar} alt="Avatar"/>
Avatar must be a part of the data object. You may have plenty of different users. All of them may have their own avatar.

2021-10-04 15:35 UTC, broshkabro commented on src/components/Userinfo/Userinfo.js
> +const user = {
You have to pass user data as a prop according to the task.

2021-10-04 15:37 UTC, broshkabro approved these changes

2021-10-04 15:38 UTC, merged